### ISSUE TITLE
Placing items in slot two with nothing in slot 1 does not eject items.

### ISSUE THREAD

**Issue by draxxris** [elytra/BitHop#4]

**Comment by LemmaEOF** [comment]
This is with the bithop, yeah? Which version are you using, 1.0.1 or 1.1?

**Comment by draxxris** [comment]
1.1

**Comment by draxxris** [comment]
I have it pointing to a TConstruct Smeltery controller

**Comment by LemmaEOF** [comment]
Yep, I'm getting the issue too. I'm afraid I'm on vacation for the rest of the week, but I can have @alexbobp take a look at it. It looks like an issue with the hopper instead of the controller; it's happening going into a normal chest as well. If I had to guess, something's wrong with [getFirstFullSlot](https://github.com/elytra/BitHop/blob/master/src/main/java/com/elytradev/bithop/tile/TileEntityBitHop.kt#L46).

**Comment by exaskye** [comment]
getCanExtract does not check whether or not a slot has contents; the condition will need to be changed to something to the effect of `getCanExtract(slot) && !getStackInSlot(slot).isEmpty()`, or a simulated `extract` for parity with getFirstEmptySlot.

**Comment by LemmaEOF** [comment]
yep, that'd do it.

**Comment by exaskye** [comment]
b9cf8f93

Try this dev build to see if the issue is fixed: https://ci.elytradev.com/job/elytra/job/BitHop/job/master/42/

**Comment by LemmaEOF** [comment]
Hm, it looks like you'll want https://ci.elytradev.com/job/elytra/job/BitHop/job/master/43/ instead of 42. 42 put it in FluxHop, 43 has it in FluxHop and BitHop.

**Comment by alexbobp** [comment]
oops sorry... I wasn't paying enough attention and assumed it was common code. (I will likely refactor it so it is, I love me the common code)

**Comment by LemmaEOF** [comment]
Confirmed fixed.
